/*
 * Copyright (c) 2010, Oracle. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Oracle nor the names of its contributors
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

package waitinglist;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public class Find extends javax.swing.JFrame {
    
    /*
        Static variable
    */
    int waitingListCount = 0 ;
    int eligableListCount = 0 ;
    boolean needPrioritize = true;
//    static int availSeats = 0;
//    static int studentSelected = 0;
    static DefaultListModel waitingListModel = new DefaultListModel();
    static DefaultListModel eligibleListModel = new DefaultListModel();
    static DefaultListModel finalListModel = new DefaultListModel();
    
    static WLSWaitingTableModel waitingListTableModel = new WLSWaitingTableModel();
    static WLSEligibleTableModel eligibleListTableModel = new WLSEligibleTableModel();
    
    /** Creates new form Find */
    public Find() {
        initComponents();
        getCourses();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCourseComboBox = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        seatsAvailTextField = new javax.swing.JTextField();
        seatsAvailLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CWIDLabel1 = new javax.swing.JLabel();
        jAddStudentButton = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPrioritizeButton = new javax.swing.JButton();
        jDeleteStudentButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jEnrollButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSignOutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jLayeredPane1Layout = new org.jdesktop.layout.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waiting List Prioritizing Software");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(918, 718));
        setResizable(false);
        getContentPane().setLayout(null);

        jOptionPane1.setMessage("Are you sure you want to delete this students ? ");
        getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new Color(0,0,0,0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(204, 204, 255)));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Step 1 : Choose the course");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Course");

        jCourseComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jCourseComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCourseComboBoxMouseClicked(evt);
            }
        });
        jCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCourseComboBoxActionPerformed(evt);
            }
        });
        jCourseComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCourseComboBoxFocusGained(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .add(30, 30, 30)
                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCourseComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 430, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jCourseComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(73, 73, 73))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 100, 850, 50);

        jPanel6.setBackground(new Color(102,153,255,20));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(204, 204, 255)));

        seatsAvailTextField.setBackground(new java.awt.Color(204, 204, 255));
        seatsAvailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsAvailTextFieldActionPerformed(evt);
            }
        });
        seatsAvailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seatsAvailTextFieldKeyTyped(evt);
            }
        });

        seatsAvailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seatsAvailLabel.setForeground(new java.awt.Color(255, 255, 255));
        seatsAvailLabel.setText("Seats available");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 51));
        jLabel12.setText("Step 2 : Type avaliable seats");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel12)
                .add(132, 132, 132)
                .add(seatsAvailLabel)
                .add(26, 26, 26)
                .add(seatsAvailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(seatsAvailLabel)
                    .add(seatsAvailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(53, 53, 53))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(30, 150, 850, 50);

        jPanel4.setBackground(new Color(102,153,255,20));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(204, 204, 255)));

        CWIDLabel1.setBackground(new java.awt.Color(102, 153, 255));
        CWIDLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CWIDLabel1.setForeground(new java.awt.Color(255, 255, 255));
        CWIDLabel1.setText("CWID");

        jAddStudentButton.setText("Add");
        jAddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddStudentButtonActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CWID", "First Name", "Last Name", "Unit Completed", "Visa Status", "Current units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jPrioritizeButton.setBackground(new java.awt.Color(0, 51, 102));
        jPrioritizeButton.setForeground(new java.awt.Color(255, 255, 255));
        jPrioritizeButton.setText("Prioritize");
        jPrioritizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrioritizeButtonActionPerformed(evt);
            }
        });

        jDeleteStudentButton.setBackground(new java.awt.Color(0, 51, 102));
        jDeleteStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        jDeleteStudentButton.setText("Delete");
        jDeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteStudentButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Waiting list");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("Step 3 : Type CWID and click add ");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 51));
        jLabel16.setText("Step 4 : Click on periortize or delete ");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jDeleteStudentButton)
                        .add(18, 18, 18)
                        .add(jPrioritizeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane2)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(398, 398, 398)
                                .add(jLabel10)
                                .add(32, 32, 32)
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel13)
                                .add(87, 87, 87)
                                .add(CWIDLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jAddStudentButton)
                        .add(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel13)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(CWIDLabel1)
                            .add(jAddStudentButton))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jPrioritizeButton)
                    .add(jDeleteStudentButton)
                    .add(jLabel16))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 200, 850, 250);

        jPanel5.setBackground(new Color(102,153,255,50));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(204, 204, 255)));

        jEnrollButton.setBackground(new java.awt.Color(0, 51, 102));
        jEnrollButton.setForeground(new java.awt.Color(255, 255, 255));
        jEnrollButton.setActionCommand("Enroll");
        jEnrollButton.setLabel("Enroll");
        jEnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnrollButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 51));
        jLabel14.setText("Step 5 : Choose students and enroll");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check", "CWID", "First Name", "Last Name", "Unit completed", "Visa Status", "Current units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Eligible students");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 51));
        jLabel17.setText("Step 6 : Click on enroll");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel14)
                        .add(114, 114, 114)
                        .add(jLabel15)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jEnrollButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jEnrollButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(29, 29, 29))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 450, 850, 210);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 236, 253));
        jLabel2.setText("Waiting List Prioritizing Software");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 70, 290, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/waitinglist/csuf-logo-header.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 280, 70);

        jSignOutButton.setBackground(new java.awt.Color(0, 51, 102));
        jSignOutButton.setForeground(new java.awt.Color(255, 255, 255));
        jSignOutButton.setText("Sign out");
        jSignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSignOutButton);
        jSignOutButton.setBounds(790, 20, 90, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/waitinglist/WLS-Background.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(918, 702));
        jLabel3.setMinimumSize(new java.awt.Dimension(918, 702));
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 700));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -130, 1000, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCourseComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCourseComboBoxMouseClicked

    }//GEN-LAST:event_jCourseComboBoxMouseClicked

    private void jCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCourseComboBoxActionPerformed

    }//GEN-LAST:event_jCourseComboBoxActionPerformed

    private void jCourseComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCourseComboBoxFocusGained
        //            getCourses();
        System.out.println("could change course!!!!!!!!!!!!!!!!!!!!!!!!!!");
    }//GEN-LAST:event_jCourseComboBoxFocusGained

    private void seatsAvailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsAvailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsAvailTextFieldActionPerformed

    private void seatsAvailTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsAvailTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
            System.out.println("Just number !!!!!");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_seatsAvailTextFieldKeyTyped

    private void jAddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddStudentButtonActionPerformed
        try {

            String cwid = jTextField3.getText();

            Boolean findCwid = false;
            if (cwid.length() <= 0){
                JOptionPane.showMessageDialog(rootPane, "please enter the correct value");
            }else{
                //Check if insert sid exist in waiting list
                for (int i = 0; i < waitingListModel.getSize(); i++ ){
                    Students aStudent = (Students)waitingListModel.getElementAt(i);
                    if (aStudent.getCwid() == Integer.parseInt(cwid)){
                        findCwid = true;
                        System.out.println("Find something same");
                    }
                }
                if (findCwid == false){
                    Students aStudents = queryCwidFromDatabase(cwid);
                    if (aStudents != null){
                        waitingListModel.insertElementAt(aStudents, waitingListCount);
                        waitingListCount++;
                        waitingListTableModel.addRow(new Object[]{
                            aStudents.getCwid(), aStudents.getFName(), aStudents.getLName(),
                            aStudents.getUnitsCompleted(), aStudents.getVisaType(),
                            aStudents.getCurrentUnits()});
                        jTable3.setModel(waitingListTableModel);
                        //Clean text field
                        jTextField3.setText("");
                        needPrioritize = true;
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "CWID " + cwid + " does not exist, "
                            + "please enter the correct value");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "CWID " + cwid + " already in list",
                    "Inane error", JOptionPane.WARNING_MESSAGE);
            }
        }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
        }
        String counter = Integer.toString(waitingListCount) ;
        jLabel1.setText(counter);
    }//GEN-LAST:event_jAddStudentButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
            System.out.println("Just number !!!!!");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jPrioritizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrioritizeButtonActionPerformed

        Students [] waitingList = getWaitingList();

//        Classes abcTest = (Classes)jCourseComboBox.getSelectedItem();
//        System.out.println("Perioritize - combobox : " + abcTest + ", seatsAvailTextField:");
        if (seatsAvailTextField.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Input available seats",
                "Inane error", JOptionPane.INFORMATION_MESSAGE);
//        }else if (jCourseComboBox.getSelectedItem() != null ){
        }else{
            //            availSeats = Integer.parseInt(seatsAvailTextField.getText());
            int availSeats = getAvailSeats();
            Students [] perioritizeList = perioritize(waitingList);
            eligibleListModel.removeAllElements();
            eligableListCount = 0;
            int countexistTable = eligibleListTableModel.getRowCount();
            System.out.println("the eligableListTableModel count : " + countexistTable);
            for (int i = countexistTable ; i > 0  ; i--){
                System.out.println("Remove : " + i);
                eligibleListTableModel.removeRow(i-1);
            }
            float lastWeight = 0;
            boolean isAdded = false;
            for (int i = 0; i < perioritizeList.length; i ++)
            {
                isAdded = false;
                Students aStudent = perioritizeList[i];
                if (eligableListCount < availSeats){
                    eligibleListModel.insertElementAt(aStudent, eligableListCount);
                    eligableListCount++;
                    eligibleListTableModel.addRow(new Object[]{aStudent.getSelected(), aStudent.getCwid(),
                        aStudent.getFName(), aStudent.getLName(), aStudent.getUnitsCompleted(),
                        aStudent.getVisaType(), aStudent.getCurrentUnits()});
                lastWeight = aStudent.getWeight();
                isAdded = true;
            }
            //If next one weight == last one ... add to list
            if (lastWeight == aStudent.getWeight() && isAdded == false ){
                System.out.println(" ===== Same weight ======= :  " + i);
                eligibleListModel.insertElementAt(aStudent, eligableListCount);
                eligableListCount++;
                eligibleListTableModel.addRow(new Object[]{aStudent.getSelected(), aStudent.getCwid(),
                    aStudent.getFName(), aStudent.getLName(), aStudent.getUnitsCompleted(),
                    aStudent.getVisaType(), aStudent.getCurrentUnits()});
                lastWeight = aStudent.getWeight();
                isAdded = true;
                
            }
        }
        jTable2.setModel(eligibleListTableModel);
        needPrioritize = false;
    }
//        else{
//        JOptionPane.showMessageDialog(rootPane, "Choose one course",
//            "Inane error", JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_jPrioritizeButtonActionPerformed

    private void jDeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteStudentButtonActionPerformed

        int indexNew = jTable3.getSelectedRow();
        if (indexNew < 0){
            JOptionPane.showMessageDialog(rootPane, "You should choose one item",
                "Inane error", JOptionPane.WARNING_MESSAGE);
        }
        else{
            waitingListModel.removeElementAt(indexNew);
            waitingListCount--;
            jLabel1.setText(Integer.toString(waitingListCount));

            waitingListTableModel.removeRow(indexNew);
            needPrioritize = true;

        }
        
    }//GEN-LAST:event_jDeleteStudentButtonActionPerformed
    /*
        Enrolled Button Pressed
    */
    private void jEnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnrollButtonActionPerformed

        Students [] eligableList = getEligibleWaitingList();
        String NOT_SELECTABLE_OPTION = "- Select a course -";
        
        
        if ( needPrioritize == true){
            JOptionPane.showMessageDialog(rootPane, "Please Prioritize first",
                "Inane error", JOptionPane.WARNING_MESSAGE);
        }else if ( eligableList.length == 0 ){
            System.out.println("No student in eligiable list, please check");
            JOptionPane.showMessageDialog(rootPane, "No student in eligiable list, please check",
                "Inane error", JOptionPane.WARNING_MESSAGE);
        }else if (Find.getAvailSeats() < Find.getStudentsSelected()){
            JOptionPane.showMessageDialog(rootPane, "You selected too much students than available,"
                + "Please unselect some",
                "Inane error", JOptionPane.WARNING_MESSAGE);
        }else if (jCourseComboBox.getSelectedItem().equals(NOT_SELECTABLE_OPTION)){
            JOptionPane.showMessageDialog(rootPane, "Please select a course",
                "Inane error", JOptionPane.WARNING_MESSAGE);
            System.out.println("You should choose a course");
        }else{
            try {
                EnrollNew(eligableList);
            } catch (SQLException ex) {
                Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jEnrollButtonActionPerformed

    private void jSignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignOutButtonActionPerformed
        //Clean all models

        cleanALLModel();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dispose();
                new LoginScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_jSignOutButtonActionPerformed


   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginScreen().setVisible(true);
//                new Find().setVisible(true);
            }
        });
        
    }

    public boolean Login (String user , String pass){
          return false;
    }
    
    public void cleanALLModel(){
        waitingListCount = 0 ;
        eligableListCount = 0 ;
//        availSeats = 0;
        waitingListModel.removeAllElements();
        eligibleListModel.removeAllElements();
        finalListModel.removeAllElements();
        
        for (int i = waitingListTableModel.getRowCount() ; i > 0  ; i--){
//            System.out.println("Remove : " + i);
            waitingListTableModel.removeRow(i-1);
        }
        
        for (int i = eligibleListTableModel.getRowCount() ; i > 0  ; i--){
//            System.out.println("Remove : " + i);
            eligibleListTableModel.removeRow(i-1);
        }
    }
    
    public Students queryCwidFromDatabase(String aCwid) throws SQLException, ClassNotFoundException{
        Students aStudent = null;
        try (Connection con = DriverManager.getConnection(WLConfig.DB_URL, 
                WLConfig.databaseUser, WLConfig.databasePassword)) {
            java.sql.Statement st = con.createStatement();
            String sql = ("SELECT * FROM student WHERE cwid = "+aCwid+";");
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                 aStudent = new Students(
                        rs.getInt("cwid"),
                        rs.getNString("fname"),
                        rs.getNString("lname"),
                        rs.getInt("units_completed"),
                        rs.getInt("visa"),
                        rs.getInt("current_units"),
                        rs.getFloat("weight"));
            }
        }
        return aStudent;
    }
    
    /*
        This method is for get waiting list
    */
    public Students [] getWaitingList() {
        Students [] studentsArray = new Students[waitingListModel.getSize()];
        for ( int i = 0 ; i < waitingListModel.getSize() ; i++){
            studentsArray[i]  =  (Students)waitingListModel.getElementAt(i) ;
        }
        return studentsArray;
    }
    
    /*
        This method is for get eligable waiting list
    */
    public Students [] getEligibleWaitingList(){
        Students[] studentsArray = new Students[eligibleListModel.getSize()];
        int isSelectedCount = 0;
        finalListModel.removeAllElements();
        for ( int i = 0 ; i < eligibleListModel.getSize() ; i++){
            studentsArray[i] = (Students)eligibleListModel.getElementAt(i);
            if (studentsArray[i].getSelected()){
                System.out.println("eligible students : " + studentsArray[i].toString() + 
                        ", selected : " + studentsArray[i].getSelected());
                finalListModel.insertElementAt(studentsArray[i], isSelectedCount);
                isSelectedCount++;
            }
        }
        Students[] studentsFinalArray = new Students[finalListModel.getSize()];
        for ( int i = 0 ; i < finalListModel.getSize() ; i++){
            studentsFinalArray[i] = (Students)finalListModel.getElementAt(i);
        }
        
        return studentsFinalArray;
    }

    public Students [] perioritize (Students [] IDList) {
        
        Students[] studentArray = new Students[IDList.length];
        int [] unitcompleted  = new int[IDList.length];
        int [] visa  = new int[IDList.length];
        int [] currentunit  = new int[IDList.length];
        
        for ( int i = 0 ; i < IDList.length ; i ++ ){
            unitcompleted[i] = IDList[i].getUnitsCompleted();
            visa[i]          = IDList[i].getVisa();
            currentunit[i]   = IDList[i].getCurrentUnits();
        }
        studentArray = calculateWeight(IDList, unitcompleted, visa, currentunit);
        
        Arrays.sort(studentArray, Students.WeightComparator);
        System.out.println("Students list sorted by unitsCompleted:\n" + Arrays.toString(studentArray));
        
        return studentArray;
    }

    /*
        Calculate student's weight and store weight in student object
    */
    public Students[] calculateWeight (Students[] aStudentArray, int[] aList, int[] bList, int[] cList){
        Students[] studentArray = aStudentArray;
        int [] minMaxA = WLToolBox.getMaxMin(aList);
        int [] minMaxB = WLToolBox.getMaxMin(bList);
        int [] minMaxC = WLToolBox.getMaxMin(cList);
        
        for (int i = 0; i < studentArray.length ; i++){
            Students abc = studentArray[i];
            float weightResult = 
                    ( (float)( abc.getUnitsCompleted() - minMaxA[0] ) / minMaxA[2] ) * WLConfig.unitCompletedWeight+
                    ( (float)( abc.getVisa() - minMaxB[0] ) / minMaxB[2] ) * WLConfig.visaWeight +
                    ( (float)( abc.getCurrentUnits() - minMaxC[0] ) / minMaxC[2] * WLConfig.currentUnitsWeight);
            abc.setWeight(weightResult);
        }
        
        return studentArray;
    }
 
    public static int getAvailSeats (){
        return Integer.parseInt(seatsAvailTextField.getText());
    }
    
    public static int getStudentsSelected(){
        Students[] studentsArray = new Students[eligibleListModel.getSize()];
        int studentSelected = 0;
        for ( int i = 0 ; i < eligibleListModel.getSize() ; i++){
            studentsArray[i] = (Students)eligibleListModel.getElementAt(i);
            if (studentsArray[i].getSelected()){
//                System.out.println("eligible students : " + studentsArray[i].toString() + 
//                        ", selected : " + studentsArray[i].getSelected());
                studentSelected++;
            }
        }
        return studentSelected;
    }
    /**
     *
     */
    public void getCourses(){
        try {
            jCourseComboBox.removeAllItems();
            Classes[] classArray = getCoursesFromDatabase();
            String NOT_SELECTABLE_OPTION = "- Select a course -";
            jCourseComboBox.addItem(NOT_SELECTABLE_OPTION);
            for ( int i = 0 ; i < classArray.length ; i++){
                jCourseComboBox.addItem(classArray[i]);
            }  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public  Classes[] getCoursesFromDatabase() throws ClassNotFoundException, SQLException{
        
        int queryCount = 0;
        Connection con = DriverManager.getConnection(WLConfig.DB_URL, 
                WLConfig.databaseUser, WLConfig.databasePassword);
        java.sql.Statement st2 = con.createStatement();
        String sql2 = ("SELECT * FROM Courses;");
        ResultSet rs2 = st2.executeQuery(sql2);
        Classes[] classArray = new Classes[WLToolBox.getDatabaseRowCount(rs2)];
        while (rs2.next()){
            classArray[queryCount] = new Classes(rs2.getString("CourseName"), 
                                        rs2.getInt("Section"),
                                        rs2.getString("SectionDetail"),
                                        rs2.getInt("ClassNumber"),
                                        rs2.getString("DayTime"),
                                        rs2.getString("Room"),
                                        rs2.getString("Instructor"),
                                        rs2.getString("MeetingDate"));
            
            queryCount++;
        }
        con.close();
        return classArray;
    }
    
    /*
        Step1. get list from eliable list
        Step2. retrieve information from db
        Step3. get selected course
        Step4. insert number of eliable students into selected course(table)
    */
    public Students [] EnrollNew (Students [] eligableList) throws SQLException{
        Classes aClass = (Classes)jCourseComboBox.getSelectedItem();
        System.out.println("Enroll - selected course : " + aClass.toString());
        JScrollPane scrollpane = new JScrollPane(); 
        ArrayList<String> categories = new ArrayList<String>();
        categories.add(aClass.toString());
        for (int i = 0 ; i < eligableList.length ; i++){
            categories.add(eligableList[i].print());
        }
        JList list = new JList(categories.toArray());
        scrollpane = new JScrollPane(list);
        JPanel panel = new JPanel(); 
        panel.add(scrollpane);
        scrollpane.getViewport().add(list);
        
        Object[] options = {"OK", "Cancel"};
        int n = JOptionPane.showOptionDialog(rootPane,//parent container of JOptionPane
            scrollpane,
            "Confirm enroll students list",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,//do not use a custom Icon
            options,//the titles of buttons
            options[1]);//default button title
        System.out.println("you choose : " + n); //Canel --> 1, OK --> 0
        if (n == 0){ //
            writeDatabase(aClass, eligableList);
            updateStudentCurrentUnit(eligableList);
            resetData();
        }else{
            //do nothing....
        }
        return null;
    }

    public void writeDatabase (Classes aClass, Students[] eligableList) throws SQLException{

        try (Connection con = DriverManager.getConnection(WLConfig.DB_URL, 
                WLConfig.databaseUser, WLConfig.databasePassword)) {
            java.sql.Statement st = con.createStatement();
            
            String tableName = aClass.getShortName();
            String query = "DROP Table IF EXISTS " + tableName;
            st.executeUpdate(query);
            
            String sql = "CREATE TABLE " + tableName +  "(id INTEGER(9)not NULL)";
            st.executeUpdate(sql);
            
            for (int i = 0; i < eligableList.length ; i ++){
                String insert = "INSERT " + tableName + " VALUES(" + eligableList[i].getCwid() + ")";
                st.executeUpdate(insert);
            }
            con.close();

            //success to write database
            JOptionPane.showMessageDialog(rootPane, "Update class data success", 
                    "System Message", JOptionPane.PLAIN_MESSAGE);
            
        }
  
    }
    
    public void updateStudentCurrentUnit (Students[] eligableList) throws SQLException{
        try (Connection con = DriverManager.getConnection("jdbc:mysql://" 
            + WLConfig.serverIP +":" + WLConfig.serverPort + "/" + WLConfig.database, 
                WLConfig.databaseUser, WLConfig.databasePassword)) {
            java.sql.Statement st = con.createStatement();
            
            for (int i = 0; i < eligableList.length ; i ++){
                int finalUnits = eligableList[i].getCurrentUnits() + 3;
                String sql = ("UPDATE student SET current_units = '" + finalUnits + "' where cwid = '" + eligableList[i].getCwid() + "';");
                System.out.println("Sql string : " + sql);
                st.executeUpdate(sql);
            }
            con.close();
        }
        
    }
    public void resetData(){
        cleanALLModel();
        seatsAvailTextField.setText("");
        jCourseComboBox.setSelectedIndex(0);
        jLabel1.setText(Integer.toString(waitingListCount));
        needPrioritize = true;
//        setSelectedItem
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CWIDLabel1;
    private javax.swing.JButton jAddStudentButton;
    private javax.swing.JComboBox jCourseComboBox;
    private javax.swing.JButton jDeleteStudentButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JButton jEnrollButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jPrioritizeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jSignOutButton;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel seatsAvailLabel;
    private static javax.swing.JTextField seatsAvailTextField;
    // End of variables declaration//GEN-END:variables
    
}
